### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by dtelaroli** [TonGarcia/ionic2-devise-token-auth#1]
Is it possible create some documentation to use?

**Comment by TonGarcia** [comment]
Hello @dtelaroli,
Now you have a link on the [Readme](https://github.com/TonGarcia/ionic2-devise-token-auth/blob/master/README.md) to the [DocFile](https://github.com/TonGarcia/ionic2-devise-token-auth/blob/master/DocFile.md) which have it explanation on how to install and how to use.
